#!/var/opt/UNItools/bin/bash
#
# $Header: /lan/ssi/shared/software/internal/i2drd/src/GaIA/drd,v 1.2 2016/06/16 11:01:30 root Exp root $
#
# Copyright (c) 2016 Niels Thomas Haugård. All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF I2/DTU, DENMARK
# The copyright notice above does not evidence  any  actual  or
# intended publication of such source code.
#
# chkconfig: 2345 55 25
# description: Some DEiC i2 start up script
#

SN=drd
PKG=i2${SN}
PORT=8088

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Source CP specific configuration
. /tmp/.CPprofile.sh

# Source the rest
. /home/admin/.bash_profile

# Check that networking is up.
[ ${NETWORKING} = "no" ]        && exit 1

PROG=/web/cpshared/web/Apache/2.2.0/bin/httpd2

SERVER=/web/cpshared/web/Apache/2.2.0/bin/httpd2

PROD_DIR=/var/opt/$PKG
RUNME=${PROD_DIR}/bin/runme.sh

RC=${PROD_DIR}/etc/${SN}

CONFIG=${PROD_DIR}/etc/httpd2.conf
IPADDR=${PROD_DIR}/etc/.listen_ip.txt

ARGS=" -D FOREGROUND"


case "$1" in
	setup)
		# install cron + init.d + make html config file
		echo creating /etc/cron.d/${SN} ...
		cat << EOF > /etc/cron.d/${SN}
59 13 * * * root [ -x ${RUNME} ] && ${RUNME}
EOF
		chmod 0640 /etc/cron.d/${DN}
		chown root:root /etc/cron.d/${DN}
		/etc/init.d/crond restart >/dev/null 2>&1

		echo creating /etc/init.d/${SN} ...
		/bin/cp ${PROD_DIR}/etc/${SN} /etc/init.d/${SN}
		chkconfig --add ${SN}
		chkconfig --list ${SN}

		echo checking links ... 
		for LINK in ismodules modules
		do
			if [ ! -h $PROD_DIR/data/$LINK ]; then
				if [ ! -e  $PROD_DIR/data/$LINK ]; then
					echo "creating sym link /web/$LINK $PROD_DIR/data/$LINK"
					ln -s /web/$LINK $PROD_DIR/data/$LINK
				else
					echo "warn: $PROD_DIR/data/$LINK should be a link"
				fi
			fi
		done
		ln -sf /opt/CPshrd-R77/web/Apache/2.2.0/conf $PROD_DIR/data/conf

		echo  "setting mode correctly ..."
		(
			cd $PROD_DIR;
			chmod 755 . data
			find data -type d	| xargs chmod 755
			find data -type f	| xargs chmod 744
		)

		echo "CONFIG=${CONFIG}"
		echo "creating `basename ${CONFIG}` from `basename ${CONFIG}.tmpl` ... "

		if [ -f "${IPADDR}" ]; then
			LISTEN_IP="`cat ${IPADDR}`"
			echo "found file ${IPADDR}"
			echo "listen ip = $LISTEN_IP"
		else
			if [ -f "${CONFIG}" ]; then
				LISTEN_IP=`sed " /^Listen/!d; s/^Listen//; s/:.*//; s/^[ \t]*//; s/[ \t]*$//; " ${CONFIG}`
				echo ${LISTEN_IP} > ${IPADDR}
			else
				LISTEN_IP="127.0.0.1"
			fi
			echo "listen ip = $LISTEN_IP - please change in ${CONFIG}"
		fi

		SERVER_ROOT="/var/opt/${PKG}/data"
		PID_FILE="/var/opt/${PKG}/tmp/httpd2.pid"
		SBFILE="/var/opt/${PKG}/tmp/apache_runtime_status"
		DOCUMENT_ROOT="/var/opt/${PKG}/data/html"
		SERVER_NAME="`/bin/hostname`.`/bin/domainname`"

		sed "
			s%__SERVER_ROOT__%${SERVER_ROOT}%g;
			s%__PID_FILE__%${PID_FILE}%g;
			s%__SBFILE__%${SBFILE}%g;
			s%__DOCUMENT_ROOT__%${DOCUMENT_ROOT}%g;
			s%__SERVER_NAME__%${SERVER_NAME}%g;
			s%__LISTEN_IP__%${LISTEN_IP}%g;
			s%__PORT__%${PORT}%g;
		" ${CONFIG}.tmpl > ${CONFIG}

	;;
        start)  $SERVER -k start -f $CONFIG $ARGS &
                RETVAL=$?
        ;;
        stop)   pids=`ps -fe | sed "\%${SERVER}%!d; \%${CONFIG}%!d; /\\%/d " | awk '{ print $2 }'`
		if [ -n  "$pids" ]; then
			kill -9 $pids
		fi
                RETVAL=$?
         ;;

        status) pids=`ps -fe | sed "\%${SERVER}%!d; \%${CONFIG}%!d; /\\%/d " | awk '{ print $2 }'`
		pids=`echo ${pids}`
                case "${pids}" in
                        "")     echo "$PROG not running"
                        ;;
                        *)      echo "$PKG is running on pid $pids"
                        ;;
                        esac
        ;;
        restart) $RC stop; $RC start
        ;;
        *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
